# Generated by Django 4.2.23 on 2025-07-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
