# Generated by Django 4.2.23 on 2025-08-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_reminder_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.jobapplication'),
        ),
    ]
